### ISSUE TITLE
macos is an Unrecognized platform

### ISSUE THREAD

**Issue by MonFig** [ptmt/react-native-macos#175]
I have a React-Native project and a React-Native-macOS project in my workspace. The issue is that when I compile the macOS project,  the terminal has an output says that 
```
Error: Unrecognized platform: macos
    at DependencyGraph._getRequestPlatform (/Users/username/workspace/theiOSProgram/node_modules/react-native/packager/src/node-haste/index.js:334:13)
    at load.then (/Users/username/workspace/theiOSProgram/node_modules/react-native/packager/src/node-haste/index.js:294:23)
    at process._tickCallback (internal/process/next_tick.js:103:7)
(node:55925) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5658): Error: Unrecognized platform: macos
```
Here some useful information about my environment:
- macos version: 10.12.6
- Xcode version: 8.3.2 (8E2002)
- react-native-cli: 2.0.1
- react-native-macos-cli: 2.0.1
- react-native-macos: 0.16.0

Thanks!

**Comment by MonFig** [comment]
Solved by remove all node_moudles folders and run `npm install` instead.

I'm afraid it's a yarn issue.
