### ISSUE TITLE
`react-native-macos init MyProject` fails.

### ISSUE THREAD

**Issue by bslayerw** [ptmt/react-native-macos#248]
## 🐛 Bug Report
I cannot create a new project. 
(A clear and concise description of what the bug is.)

```react-native-macos init MyProject                                                                                                                                                INT ✘  12.16.0   19:02:38 

This will walk you through creating a new React Native for macOS project in /Users/byronwright/Projects/MyProject
Using yarn v1.21.1
Installing react-native-macos...
yarn add v1.21.1
info No lockfile found.
[1/4] 🔍  Resolving packages...
warning react-native-macos > fbjs-scripts > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning react-native-macos > fbjs > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning react-native-macos > create-react-class > fbjs > core-js@1.2.7: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning react-native-macos > metro-babel-register > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "react-native-macos > @react-native-community/cli@2.10.0" has unmet peer dependency "react-native@^0.60.0".
warning "react-native-macos > metro-react-native-babel-transformer@0.54.1" has unmet peer dependency "@babel/core@*".
warning " > react-native-macos@0.60.0-microsoft.50" has unmet peer dependency "react@16.8.6".
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
success Saved 423 new dependencies.
info Direct dependencies
└─ react-native-macos@0.60.0-microsoft.50
info All dependencies
├─ @babel/code-frame@7.8.3
├─ @babel/helper-builder-binary-assignment-operator-visitor@7.8.3
├─ @babel/helper-builder-react-jsx@7.8.3
├─ @babel/helper-call-delegate@7.8.3
├─ @babel/helper-create-regexp-features-plugin@7.8.3
├─ @babel/helper-define-map@7.8.3
├─ @babel/helper-explode-assignable-expression@7.8.3
├─ @babel/helper-hoist-variables@7.8.3
├─ @babel/helper-module-imports@7.8.3
├─ @babel/helper-module-transforms@7.8.3
├─ @babel/helper-remap-async-to-generator@7.8.3
├─ @babel/helper-wrap-function@7.8.3
├─ @babel/helpers@7.8.4
├─ @babel/highlight@7.8.3
├─ @babel/parser@7.8.4
├─ @babel/plugin-external-helpers@7.8.3
├─ @babel/plugin-proposal-export-default-from@7.8.3
├─ @babel/plugin-syntax-class-properties@7.8.3
├─ @babel/plugin-syntax-dynamic-import@7.8.3
├─ @babel/plugin-syntax-export-default-from@7.8.3
├─ @babel/plugin-syntax-flow@7.8.3
├─ @babel/plugin-syntax-nullish-coalescing-operator@7.8.3
├─ @babel/plugin-syntax-object-rest-spread@7.8.3
├─ @babel/plugin-syntax-optional-catch-binding@7.8.3
├─ @babel/plugin-syntax-optional-chaining@7.8.3
├─ @babel/plugin-syntax-typescript@7.8.3
├─ @babel/plugin-transform-async-to-generator@7.8.3
├─ @babel/plugin-transform-block-scoped-functions@7.8.3
├─ @babel/plugin-transform-exponentiation-operator@7.8.3
├─ @babel/plugin-transform-member-expression-literals@7.8.3
├─ @babel/plugin-transform-object-assign@7.8.3
├─ @babel/plugin-transform-object-super@7.8.3
├─ @babel/plugin-transform-property-literals@7.8.3
├─ @babel/plugin-transform-react-jsx-source@7.8.3
├─ @babel/plugin-transform-regenerator@7.8.3
├─ @babel/plugin-transform-runtime@7.8.3
├─ @babel/plugin-transform-sticky-regex@7.8.3
├─ @babel/plugin-transform-typescript@7.8.3
├─ @babel/plugin-transform-unicode-regex@7.8.3
├─ @babel/register@7.8.3
├─ @babel/runtime@7.8.4
├─ @cnakazawa/watch@1.0.4
├─ @hapi/address@2.1.4
├─ @hapi/bourne@1.3.2
├─ @hapi/hoek@8.5.1
├─ @hapi/joi@15.1.1
├─ @hapi/topo@3.1.6
├─ @jest/fake-timers@24.9.0
├─ @react-native-community/cli-platform-android@2.9.0
├─ @react-native-community/cli-platform-ios@2.10.0
├─ @react-native-community/cli@2.10.0
├─ @types/istanbul-lib-report@3.0.0
├─ @types/istanbul-reports@1.1.1
├─ @types/stack-utils@1.0.1
├─ @types/yargs-parser@15.0.0
├─ @types/yargs@13.0.8
├─ abbrev@1.1.1
├─ abort-controller@3.0.0
├─ accepts@1.3.7
├─ ansi-colors@1.1.0
├─ ansi-cyan@0.1.1
├─ ansi-escapes@3.2.0
├─ ansi-fragments@0.2.1
├─ ansi-gray@0.1.1
├─ ansi-red@0.1.1
├─ ansi-regex@4.1.0
├─ aproba@1.2.0
├─ are-we-there-yet@1.1.5
├─ argparse@1.0.10
├─ arr-flatten@1.1.0
├─ array-filter@0.0.1
├─ array-map@0.0.0
├─ array-reduce@0.0.0
├─ array-slice@0.2.3
├─ art@0.10.3
├─ asap@2.0.6
├─ assign-symbols@1.0.0
├─ astral-regex@1.0.0
├─ async-limiter@1.0.1
├─ async@2.6.3
├─ atob@2.1.2
├─ babel-plugin-dynamic-import-node@2.3.0
├─ babel-plugin-syntax-trailing-function-commas@7.0.0-beta.0
├─ balanced-match@1.0.0
├─ base@0.11.2
├─ base64-js@1.3.1
├─ basic-auth@2.0.1
├─ big-integer@1.6.48
├─ bindings@1.5.0
├─ bplist-creator@0.0.8
├─ bplist-parser@0.2.0
├─ brace-expansion@1.1.11
├─ braces@2.3.2
├─ bser@2.1.1
├─ buffer-crc32@0.2.13
├─ bytes@3.0.0
├─ cache-base@1.0.1
├─ caller-callsite@2.0.0
├─ caller-path@2.0.0
├─ capture-exit@2.0.0
├─ chardet@0.4.2
├─ chownr@1.1.4
├─ ci-info@2.0.0
├─ class-utils@0.3.6
├─ cli-spinners@2.2.0
├─ cli-width@2.2.0
├─ cliui@3.2.0
├─ clone@1.0.4
├─ code-point-at@1.1.0
├─ collection-visit@1.0.0
├─ color-convert@1.9.3
├─ color-name@1.1.3
├─ color-support@1.1.3
├─ colorette@1.1.0
├─ commander@2.20.3
├─ commondir@1.0.1
├─ compressible@2.0.18
├─ compression@1.7.4
├─ concat-map@0.0.1
├─ concat-stream@1.6.2
├─ console-control-strings@1.1.0
├─ convert-source-map@1.7.0
├─ copy-descriptor@0.1.1
├─ core-js@2.6.11
├─ core-util-is@1.0.2
├─ cosmiconfig@5.2.1
├─ create-react-class@15.6.3
├─ cross-spawn@5.1.0
├─ dayjs@1.8.20
├─ debug@2.6.9
├─ decode-uri-component@0.2.0
├─ deep-extend@0.6.0
├─ deepmerge@3.3.0
├─ defaults@1.0.3
├─ define-properties@1.1.3
├─ delegates@1.0.0
├─ denodeify@1.2.1
├─ destroy@1.0.4
├─ detect-libc@1.0.3
├─ dom-walk@0.1.1
├─ ee-first@1.1.1
├─ encoding@0.1.12
├─ end-of-stream@1.4.4
├─ envinfo@7.5.0
├─ error-ex@1.3.2
├─ errorhandler@1.5.1
├─ esprima@4.0.1
├─ esutils@2.0.3
├─ etag@1.8.1
├─ event-target-shim@5.0.1
├─ eventemitter3@3.1.2
├─ expand-brackets@2.1.4
├─ external-editor@2.2.0
├─ extglob@2.0.4
├─ fancy-log@1.3.3
├─ fbjs-css-vars@1.0.2
├─ fbjs-scripts@1.2.0
├─ figures@2.0.0
├─ file-uri-to-path@1.0.0
├─ fill-range@4.0.0
├─ finalhandler@1.1.2
├─ find-cache-dir@2.1.0
├─ for-in@1.0.2
├─ fresh@0.5.2
├─ fs-extra@7.0.1
├─ fs-minipass@1.2.7
├─ fs.realpath@1.0.0
├─ fsevents@1.2.11
├─ function-bind@1.1.1
├─ gauge@2.7.4
├─ gensync@1.0.0-beta.1
├─ get-stream@4.1.0
├─ get-value@2.0.6
├─ glob@7.1.6
├─ global@4.4.0
├─ growly@1.3.0
├─ has-symbols@1.0.1
├─ has-unicode@2.0.1
├─ has-value@1.0.0
├─ hermesvm@0.1.1
├─ hosted-git-info@2.8.5
├─ http-errors@1.7.3
├─ iconv-lite@0.4.24
├─ ignore-walk@3.0.3
├─ image-size@0.6.3
├─ import-fresh@2.0.0
├─ imurmurhash@0.1.4
├─ inflight@1.0.6
├─ inherits@2.0.4
├─ ini@1.3.5
├─ inquirer@3.3.0
├─ invert-kv@1.0.0
├─ is-accessor-descriptor@1.0.0
├─ is-arrayish@0.2.1
├─ is-ci@2.0.0
├─ is-data-descriptor@1.0.0
├─ is-descriptor@1.0.2
├─ is-directory@0.3.1
├─ is-plain-object@2.0.4
├─ is-promise@2.1.0
├─ is-windows@1.0.2
├─ isarray@1.0.0
├─ isexe@2.0.0
├─ jest-get-type@24.9.0
├─ jest-message-util@24.9.0
├─ jest-mock@24.9.0
├─ jest-serializer@24.9.0
├─ jest-util@24.9.0
├─ jest-validate@24.9.0
├─ jest-worker@24.9.0
├─ jetifier@1.6.5
├─ js-tokens@4.0.0
├─ js-yaml@3.13.1
├─ jsc-android@245459.0.0
├─ jsesc@2.5.2
├─ json-parse-better-errors@1.0.2
├─ json-stable-stringify@1.0.1
├─ json5@2.1.1
├─ jsonfile@4.0.0
├─ kind-of@3.2.2
├─ klaw@1.3.1
├─ lcid@1.0.0
├─ leven@3.1.0
├─ load-json-file@2.0.0
├─ locate-path@3.0.0
├─ log-symbols@2.2.0
├─ logkitty@0.6.1
├─ loose-envify@1.4.0
├─ lru-cache@4.1.5
├─ make-dir@2.1.0
├─ makeerror@1.0.11
├─ map-age-cleaner@0.1.3
├─ map-visit@1.0.0
├─ mem@1.1.0
├─ merge-stream@1.0.1
├─ metro-babel7-plugin-react-transform@0.54.1
├─ metro-config@0.54.1
├─ metro-inspector-proxy@0.54.1
├─ metro-minify-uglify@0.54.1
├─ metro-react-native-babel-transformer@0.54.1
├─ metro-source-map@0.55.0
├─ metro-symbolicate@0.55.0
├─ metro@0.54.1
├─ mime-db@1.43.0
├─ mime-types@2.1.11
├─ mime@2.4.4
├─ min-document@2.19.0
├─ minimatch@3.0.4
├─ minimist@1.2.0
├─ minipass@2.9.0
├─ minizlib@1.3.3
├─ mixin-deep@1.3.2
├─ mkdirp@0.5.1
├─ morgan@1.9.1
├─ ms@2.1.2
├─ mute-stream@0.0.7
├─ nan@2.14.0
├─ nanomatch@1.2.13
├─ needle@2.3.2
├─ negotiator@0.6.2
├─ nice-try@1.0.5
├─ node-fetch@2.6.0
├─ node-int64@0.4.0
├─ node-modules-regexp@1.0.0
├─ node-notifier@5.4.3
├─ node-pre-gyp@0.14.0
├─ nopt@4.0.1
├─ normalize-package-data@2.5.0
├─ normalize-path@2.1.1
├─ npm-bundled@1.1.1
├─ npm-packlist@1.4.8
├─ npmlog@4.1.2
├─ number-is-nan@1.0.1
├─ ob1@0.55.0
├─ object-assign@4.1.1
├─ object-copy@0.1.0
├─ object-keys@1.1.1
├─ object.assign@4.1.0
├─ on-headers@1.0.2
├─ once@1.4.0
├─ onetime@2.0.1
├─ open@6.4.0
├─ options@0.0.6
├─ ora@3.4.0
├─ os-homedir@1.0.2
├─ os-locale@2.1.0
├─ os-tmpdir@1.0.2
├─ osenv@0.1.5
├─ p-defer@1.0.0
├─ p-is-promise@2.1.0
├─ p-limit@2.2.2
├─ p-locate@3.0.0
├─ p-try@2.2.0
├─ parse-json@4.0.0
├─ parse-node-version@1.0.1
├─ pascalcase@0.1.1
├─ path-is-absolute@1.0.1
├─ path-key@2.0.1
├─ path-parse@1.0.6
├─ path-type@2.0.0
├─ pirates@4.0.1
├─ pkg-dir@3.0.0
├─ plist@3.0.1
├─ plugin-error@0.1.2
├─ posix-character-classes@0.1.1
├─ pretty-format@24.9.0
├─ private@0.1.8
├─ process-nextick-args@2.0.1
├─ process@0.11.10
├─ prop-types@15.7.2
├─ pseudomap@1.0.2
├─ pump@3.0.0
├─ range-parser@1.2.1
├─ rc@1.2.8
├─ react-deep-force-update@1.1.2
├─ react-devtools-core@3.6.3
├─ react-is@16.12.0
├─ react-native-macos@0.60.0-microsoft.50
├─ react-proxy@1.1.8
├─ read-pkg-up@2.0.0
├─ read-pkg@2.0.0
├─ readable-stream@2.3.7
├─ regenerate-unicode-properties@8.1.0
├─ regenerator-transform@0.14.1
├─ regexpu-core@4.6.0
├─ regjsgen@0.5.1
├─ regjsparser@0.6.2
├─ remove-trailing-separator@1.1.0
├─ repeat-element@1.1.3
├─ resolve-from@3.0.0
├─ resolve-url@0.2.1
├─ resolve@1.15.1
├─ restore-cursor@2.0.0
├─ ret@0.1.15
├─ rimraf@2.7.1
├─ rsvp@4.8.5
├─ run-async@2.3.0
├─ rx-lite-aggregates@4.0.8
├─ rx-lite@4.0.8
├─ rxjs@5.5.12
├─ safer-buffer@2.1.2
├─ sane@4.1.0
├─ sax@1.2.4
├─ scheduler@0.14.0
├─ semver@5.7.1
├─ send@0.17.1
├─ serialize-error@2.1.0
├─ serve-static@1.14.1
├─ set-blocking@2.0.0
├─ set-value@2.0.1
├─ setprototypeof@1.1.1
├─ shebang-regex@1.0.0
├─ shell-quote@1.6.1
├─ shellwords@0.1.1
├─ signal-exit@3.0.2
├─ simple-plist@1.1.0
├─ slice-ansi@2.1.0
├─ slide@1.1.6
├─ snapdragon-node@2.1.1
├─ snapdragon-util@3.0.1
├─ source-map-resolve@0.5.3
├─ source-map-support@0.5.16
├─ source-map-url@0.4.0
├─ spdx-correct@3.1.0
├─ spdx-exceptions@2.2.0
├─ split-string@3.1.0
├─ sprintf-js@1.0.3
├─ stack-utils@1.0.2
├─ stacktrace-parser@0.1.8
├─ static-extend@0.1.2
├─ statuses@1.5.0
├─ stream-buffers@2.2.0
├─ string_decoder@1.1.1
├─ string-width@2.1.1
├─ strip-ansi@3.0.1
├─ strip-bom@3.0.0
├─ strip-json-comments@2.0.1
├─ supports-color@5.5.0
├─ symbol-observable@1.0.1
├─ tar@4.4.13
├─ temp@0.8.3
├─ throat@4.1.0
├─ through@2.3.8
├─ through2@2.0.5
├─ time-stamp@1.1.0
├─ tmp@0.0.33
├─ to-fast-properties@2.0.0
├─ to-object-path@0.3.0
├─ to-regex-range@2.1.1
├─ toidentifier@1.0.0
├─ type-fest@0.7.1
├─ typedarray@0.0.6
├─ uglify-es@3.3.9
├─ ultron@1.0.2
├─ unicode-canonical-property-names-ecmascript@1.0.4
├─ unicode-match-property-ecmascript@1.0.4
├─ unicode-match-property-value-ecmascript@1.1.0
├─ unicode-property-aliases-ecmascript@1.0.5
├─ union-value@1.0.1
├─ universalify@0.1.2
├─ unpipe@1.0.0
├─ unset-value@1.0.0
├─ urix@0.1.0
├─ use@3.1.1
├─ util-deprecate@1.0.2
├─ utils-merge@1.0.1
├─ uuid@3.4.0
├─ validate-npm-package-license@3.0.4
├─ vary@1.1.2
├─ walker@1.0.7
├─ wcwidth@1.0.1
├─ whatwg-fetch@3.0.0
├─ wide-align@1.1.3
├─ write-file-atomic@1.3.4
├─ xcode@2.1.0
├─ xmlbuilder@9.0.7
├─ xmldoc@1.1.2
├─ xmldom@0.1.31
├─ xpipe@1.0.5
├─ xtend@4.0.2
├─ y18n@3.2.1
├─ yallist@3.1.1
└─ yargs-parser@7.0.0
✨  Done in 9.48s.
info Setting up new React Native app in /Users/byronwright/Projects/MyProject
(node:24374) UnhandledPromiseRejectionWarning: Error: Cannot find module 'react-native/package.json'
Require stack:
- /Users/byronwright/Projects/MyProject/node_modules/@react-native-community/cli/build/commands/init/initCompat.js
- /Users/byronwright/Projects/MyProject/node_modules/@react-native-community/cli/build/cliEntry.js
- /Users/byronwright/Projects/MyProject/node_modules/@react-native-community/cli/build/index.js
- /Users/byronwright/Projects/MyProject/node_modules/react-native-macos/cli.js
- /Users/byronwright/.nvm/versions/node/v12.16.0/lib/node_modules/react-native-macos-cli/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:981:15)
    at Function.Module._load (internal/modules/cjs/loader.js:863:27)
    at Module.require (internal/modules/cjs/loader.js:1043:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at generateProject (/Users/byronwright/Projects/MyProject/node_modules/@react-native-community/cli/build/commands/init/initCompat.js:114:19)
    at Object.initCompat [as init] (/Users/byronwright/Projects/MyProject/node_modules/@react-native-community/cli/build/commands/init/initCompat.js:104:9)
    at run (/Users/byronwright/.nvm/versions/node/v12.16.0/lib/node_modules/react-native-macos-cli/index.js:306:7)
    at createProject (/Users/byronwright/.nvm/versions/node/v12.16.0/lib/node_modules/react-native-macos-cli/index.js:254:3)
    at init (/Users/byronwright/.nvm/versions/node/v12.16.0/lib/node_modules/react-native-macos-cli/index.js:202:5)
    at Object.<anonymous> (/Users/byronwright/.nvm/versions/node/v12.16.0/lib/node_modules/react-native-macos-cli/index.js:155:7)
(node:24374) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:24374) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```
## To Reproduce
`react-native-macos init MyProject`
Steps to reproduce the behavior:
`react-native-macos init MyProject`
## Expected Behavior
creates a new project successfully.
(A clear and concise description of what you expected to happen.)

## Minimal Reproduction

(For bugs that cannot be reproduced within RNTester, please provide a [minimal](https://stackoverflow.com/help/mcve) repository.)

## Environment
info Fetching system and libraries information...
System:
    OS: macOS 10.15.2
    CPU: (8) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
    Memory: 101.79 MB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.0 - ~/.nvm/versions/node/v12.16.0/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 26, 27, 28
      Build Tools: 27.0.3, 28.0.3
      System Images: android-28 | Google APIs Intel x86 Atom
      Android NDK: 19.0.5232133
  IDEs:
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react-native: ^0.61.5 => 0.61.5
  npmGlobalPackages:
    create-react-native-app: 2.0.2
    react-native-macos-cli: 2.0.1

**Comment by dluc** [comment]
same here
```
(node:54011) UnhandledPromiseRejectionWarning: Error: Cannot find module 'react-native/package.json'
Require stack:
- /Users/test/workspace/me/reactnativemacos/SomeTest/node_modules/@react-native-community/cli/build/commands/init/initCompat.js
- /Users/test/workspace/me/reactnativemacos/SomeTest/node_modules/@react-native-community/cli/build/cliEntry.js
- /Users/test/workspace/me/reactnativemacos/SomeTest/node_modules/@react-native-community/cli/build/index.js
- /Users/test/workspace/me/reactnativemacos/SomeTest/node_modules/react-native-macos/cli.js
- /usr/local/lib/node_modules/react-native-macos-cli/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at generateProject (/Users/test/workspace/me/reactnativemacos/SomeTest/node_modules/@react-native-community/cli/build/commands/init/initCompat.js:114:19)
    at Object.initCompat [as init] (/Users/test/workspace/me/reactnativemacos/SomeTest/node_modules/@react-native-community/cli/build/commands/init/initCompat.js:104:9)
    at run (/usr/local/lib/node_modules/react-native-macos-cli/index.js:306:7)
    at createProject (/usr/local/lib/node_modules/react-native-macos-cli/index.js:254:3)
    at init (/usr/local/lib/node_modules/react-native-macos-cli/index.js:202:5)
    at Object.<anonymous> (/usr/local/lib/node_modules/react-native-macos-cli/index.js:155:7)
(node:54011) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:54011) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

```
# npm -v
6.13.7
# node -v
v13.8.0
# yarn -v
1.22.0
# react-native -v
react-native-cli: 2.0.1
```

**Comment by Shummy1991** [comment]
Same here
```
(node:88224) UnhandledPromiseRejectionWarning: Error: Cannot find module 'react-native/package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:613:15)
    at Function.Module._load (internal/modules/cjs/loader.js:539:25)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at generateProject (/Users/danielbali/macostest/node_modules/@react-native-community/cli/build/commands/init/initCompat.js:114:19)
    at Object.initCompat [as init] (/Users/danielbali/macostest/node_modules/@react-native-community/cli/build/commands/init/initCompat.js:104:9)
    at run (/Users/danielbali/.nvm/versions/node/v11.10.1/lib/node_modules/react-native-macos-cli/index.js:306:7)
    at createProject (/Users/danielbali/.nvm/versions/node/v11.10.1/lib/node_modules/react-native-macos-cli/index.js:254:3)
    at init (/Users/danielbali/.nvm/versions/node/v11.10.1/lib/node_modules/react-native-macos-cli/index.js:202:5)
    at Object.<anonymous> (/Users/danielbali/.nvm/versions/node/v11.10.1/lib/node_modules/react-native-macos-cli/index.js:155:7)
(node:88224) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:88224) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

node --version
v11.10.1

yarn --version
1.22.0
```

**Comment by caojianfeng** [comment]
info Setting up new React Native app in /Volumes/user/cjf/w/desktop/life_timer
(node:33596) UnhandledPromiseRejectionWarning: Error: Cannot find module 'react-native/package.json'
Require stack:
- /Volumes/user/cjf/w/desktop/life_timer/node_modules/@react-native-community/cli/build/commands/init/initCompat.js
- /Volumes/user/cjf/w/desktop/life_timer/node_modules/@react-native-community/cli/build/cliEntry.js
- /Volumes/user/cjf/w/desktop/life_timer/node_modules/@react-native-community/cli/build/index.js
- /Volumes/user/cjf/w/desktop/life_timer/node_modules/react-native-macos/cli.js
- /Users/caojianfeng/.config/yarn/global/node_modules/react-native-macos-cli/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at generateProject (/Volumes/user/cjf/w/desktop/life_timer/node_modules/@react-native-community/cli/build/commands/init/initCompat.js:114:19)
    at Object.initCompat [as init] (/Volumes/user/cjf/w/desktop/life_timer/node_modules/@react-native-community/cli/build/commands/init/initCompat.js:104:9)
    at run (/Users/caojianfeng/.config/yarn/global/node_modules/react-native-macos-cli/index.js:306:7)
    at createProject (/Users/caojianfeng/.config/yarn/global/node_modules/react-native-macos-cli/index.js:254:3)
    at init (/Users/caojianfeng/.config/yarn/global/node_modules/react-native-macos-cli/index.js:202:5)
    at Object.<anonymous> (/Users/caojianfeng/.config/yarn/global/node_modules/react-native-macos-cli/index.js:155:7)
(node:33596) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:33596) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
soukenbons-iMac:desktop caojianfeng$ node --version
v12.14.1
soukenbons-iMac:desktop caojianfeng$ yarn --version
1.12.3
soukenbons-iMac:desktop caojianfeng$ npm -v
6.13.4
soukenbons-iMac:desktop caojianfeng$ react-native -v
react-native-cli: 2.0.1
react-native: n/a - not inside a React Native project directory
soukenbons-iMac:desktop caojianfeng$ react-native-macos -v
react-native-macos-cli: 2.0.1
react-native-macos: n/a - not inside a React Native project directory
